name: Docker Build and Push

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Build the Docker image
      - name: Build the Docker image
        run: docker build --tag my-python-app .

      # Login to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Push the Docker image to DockerHub
      - name: Push the Docker image
        run: docker push my-python-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Deploy the Docker container
      - name: Deploy the container
        run: |
          docker run -d -p 5000:5000 my-python-app:latest
